#!/bin/bash
source "$ROOT_PATH/recipes/basic"
source "$LIB_PATH/mysql.sh"
source "$LIB_PATH/memcached.sh"
source "$LIB_PATH/varnish.sh"
source "$LIB_PATH/nginx.sh"
source "$LIB_PATH/php.sh"

function defaults_wordpress {
	DATABASE_PASSWORD="mydbs3cr3t"
}

function install_wordpress {
	install_basic
	install_mysql $DATABASE_PASSWORD && tune_mysql 40
	install_memcached
	install_varnish
	install_nginx
        install_fcgiwrap
	install_php5_fpm
}
