#!/bin/bash

ROOT_PATH=$(dirname $(readlink -f $0))

if [ ! -n "$1" ]; then
	echo "Usage: ./install <recipe>"
	exit 1;
fi

RECIPES_PATH="$ROOT_PATH/recipes/$1"
if [ -e $RECIPES_PATH ] ; then
	source "$RECIPES_PATH"
fi

source "$ROOT_PATH/shellstack.sh"
exec > "$ROOT_PATH/shellstack.log"
install_`echo $1`
